//frontend/src/components/ProdukData/index.jsx
export const products = {
  jaket: [
    {
      id: "jaket-1",
      image: "/asset/image/HoodiePutih1.svg",
      images: [
        "/asset/image/HoodiePutih1.svg",
        "/asset/image/HoodiePutih2.svg",
        "/asset/image/HoodiePutih3.svg",
        "/asset/image/HoodiePutih4.svg",
        "/asset/image/HoodiePutih5.svg",
      ],
      title: "Hoodie Putih",
      price: "Rp 250.000",
      sizes: ["S", "M", "L", "XL"],
      category: "jaket",
    },
    {
      id: "jaket-2",
      image: "/asset/image/HoodieCoklat1.svg",
      images: [
        "/asset/image/HoodieCoklat1.svg",
        "/asset/image/HoodieCoklat2.svg",
        "/asset/image/HoodieCoklat3.svg",
        "/asset/image/HoodieCoklat4.svg",
        "/asset/image/HoodieCoklat5.svg",
      ],
      title: "Hoodie Coklat",
      price: "Rp 250.000",
      sizes: ["S", "M", "L", "XL"],
      category: "jaket",
    },
    {
      id: "jaket-3",
      image: "/asset/image/JaketHitam.svg",
      images: [
        "/asset/image/JaketHitam.svg",
        "/asset/image/JaketHitam2.svg",
        "/asset/image/JaketHitam3.svg",
        "/asset/image/JaketHitam4.svg",
        "/asset/image/JaketHitam5.svg",
      ],
      title: "Jaket Traker Hitam",
      price: "Rp 300.000",
      sizes: ["S", "M", "L", "XL"],
      category: "jaket",
    },
    {
      id: "jaket-4",
      image: "/asset/image/JaketHijau.svg",
      images: [
        "/asset/image/JaketHijau.svg",
        "/asset/image/JaketHijau2.svg",
        "/asset/image/JaketHijau3.svg",
        "/asset/image/JaketHijau4.svg",
        "/asset/image/JaketHijau5.svg",
      ],
      title: "Jaket Traker Hijau",
      price: "Rp 300.000",
      sizes: ["S", "M", "L", "XL"],
      category: "jaket",
    },
    {
      id: "jaket-5",
      image: "/asset/image/JaketCoklat.svg",
      images: [
        "/asset/image/JaketCoklat.svg",
        "/asset/image/JaketCoklat2.svg",
        "/asset/image/JaketCoklat3.svg",
        "/asset/image/JaketCoklat4.svg",
        "/asset/image/JaketCoklat5.svg",
      ],
      title: "Jaket Traker Coklat",
      price: "Rp 300.000",
      sizes: ["S", "M", "L", "XL"],
      category: "jaket",
    },
  ],
  kaos: [
    {
      id: "kaos-1",
      image: "/asset/image/KaosPutih.svg",
      images: [
        "/asset/image/KaosPutih.svg",
        "/asset/image/KaosPutih2.svg",
        "/asset/image/KaosPutih3.svg",
        "/asset/image/KaosPutih4.svg",
        "/asset/image/KaosPutih5.svg",
      ],
      title: "Kaos Polos Putih",
      price: "Rp 100.000",
      sizes: ["S", "M", "L", "XL"],
      category: "kaos",
    },
    {
      id: "kaos-2",
      image: "/asset/image/KaosAbu.svg",
      images: [
        "/asset/image/KaosAbu.svg",
        "/asset/image/KaosAbu2.svg",
        "/asset/image/KaosAbu3.svg",
        "/asset/image/KaosAbu4.svg",
        "/asset/image/KaosAbu5.svg",
      ],
      title: "Kaos Polos Abu-abu",
      price: "Rp 100.000",
      sizes: ["S", "M", "L", "XL"],
      category: "kaos",
    },
    {
      id: "kaos-3",
      image: "/asset/image/KaosHitam.svg",
      images: [
        "/asset/image/KaosHitam.svg",
        "/asset/image/KaosHitam2.svg",
        "/asset/image/KaosHitam3.svg",
        "/asset/image/KaosHitam4.svg",
        "/asset/image/KaosHitam5.svg",
      ],
      title: "Kaos Polos Hitam",
      price: "Rp 100.000",
      sizes: ["S", "M", "L", "XL"],
      category: "kaos",
    },
    {
      id: "kaos-4",
      image: "/asset/image/KaosBiru.svg",
      images: [
        "/asset/image/KaosBiru.svg",
        "/asset/image/KaosBiru2.svg",
        "/asset/image/KaosBiru3.svg",
        "/asset/image/KaosBiru4.svg",
        "/asset/image/KaosBiru5.svg",
      ],
      title: "Kaos Polos Biru",
      price: "Rp 100.000",
      sizes: ["S", "M", "L", "XL"],
      category: "kaos",
    },
    {
      id: "kaos-5",
      image: "/asset/image/KaosMerah.svg",
      images: [
        "/asset/image/KaosMerah.svg",
        "/asset/image/KaosMerah2.svg",
        "/asset/image/KaosMerah3.svg",
        "/asset/image/KaosMerah4.svg",
        "/asset/image/KaosMerah5.svg",
      ],
      title: "Kaos Polos Merah",
      price: "Rp 100.000",
      sizes: ["S", "M", "L", "XL"],
      category: "kaos",
    },
    {
      id: "kaos-6",
      image: "/asset/image/KaosPink.svg",
      images: [
        "/asset/image/KaosPink.svg",
        "/asset/image/KaosPink2.svg",
        "/asset/image/KaosPink3.svg",
        "/asset/image/KaosPink4.svg",
        "/asset/image/KaosPink5.svg",
      ],
      title: "Kaos Polos Pink",
      price: "Rp 100.000",
      sizes: ["S", "M", "L", "XL"],
      category: "kaos",
    },
    {
      id: "kaos-7",
      image: "/asset/image/KaosSage.svg",
      images: [
        "/asset/image/KaosSage.svg",
        "/asset/image/KaosSage2.svg",
        "/asset/image/KaosSage3.svg",
        "/asset/image/KaosSage4.svg",
        "/asset/image/KaosSage5.svg",
      ],
      title: "Kaos Polos Sage",
      price: "Rp 100.000",
      sizes: ["S", "M", "L", "XL"],
      category: "kaos",
    },
    {
      id: "kaos-8",
      image: "/asset/image/KaosCoklat.svg",
      images: [
        "/asset/image/KaosCoklat.svg",
        "/asset/image/KaosCoklat2.svg",
        "/asset/image/KaosCoklat3.svg",
        "/asset/image/KaosCoklat4.svg",
        "/asset/image/KaosCoklat5.svg",
      ],
      title: "Kaos Polos Coklat",
      price: "Rp 100.000",
      sizes: ["S", "M", "L", "XL"],
      category: "kaos",
    },
  ],
  aksesoris: [
    {
      id: "aksesoris-1",
      image: "/asset/image/TopiPutih.svg",
      title: "Topi Putih",
      price: "Rp 75.000",
      category: "aksesoris",
    },
    {
      id: "aksesoris-2",
      image: "/asset/image/TopiHitam.svg",
      title: "Topi Hitam",
      price: "Rp 75.000",
      category: "aksesoris",
    },
    {
      id: "aksesoris-3",
      image: "/asset/image/DompetHitam.svg",
      title: "Dompet Hitam",
      price: "Rp 80.000",
      category: "aksesoris",
    },
    {
      id: "aksesoris-4",
      image: "/asset/image/DompetCoklat.svg",
      title: "Dompet Coklat",
      price: "Rp 80.000",
      category: "aksesoris",
    },
    {
      id: "aksesoris-5",
      image: "/asset/image/SabukHitam.svg",
      title: "Ikat Pinggang Hitam",
      price: "Rp 120.000",
      category: "aksesoris",
    },
    {
      id: "aksesoris-6",
      image: "/asset/image/SabukCoklat.svg",
      title: "Ikat Pinggang Coklat",
      price: "Rp 120.000",
      category: "aksesoris",
    },
    {
      id: "aksesoris-7",
      image: "/asset/image/ring.svg",
      title: "Cincin",
      price: "Rp 50.000",
      category: "aksesoris",
    },
    {
      id: "aksesoris-8",
      image: "/asset/image/Kalung.svg",
      title: "Kalung",
      price: "Rp 80.000",
      category: "aksesoris",
    },
  ],
};

export const getProductById = (category, id) => {
  return products[category].find((product) => product.id === id);
};

export const getAllProducts = (category) => {
  return products[category] || [];
};
